### ISSUE TITLE
Learn about Github actions

### ISSUE THREAD

**Issue by prudhomm** [feelpp/mordicus#4]
- read https://docs.github.com/en/actions
- study mordicus actions
- propose updates 
- added badges to README file

**Comment by prudhomm** [comment]
@alielarif could you add support for python 3.7 in mordicus github. actions ?

**Comment by prudhomm** [comment]
@alielarif also remove 3.10 support

**Comment by prudhomm** [comment]
could you also add the badges for python support ?

**Comment by alielarif** [comment]
The 3.7 support require python lib jschon. I tried to install it by the command "pip install jschon", but it seems not be installed properly. However, version 3.8 and 3.9 are working correctly.

**Comment by alielarif** [comment]
Waiting for the concerned branch (alielarif_doc) to be merged with the main branch.
